import { app, BrowserWindow, ipcMain, nativeTheme, screen } from 'electron'

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const CLIENT_WINDOW_WEBPACK_ENTRY: string

process.env.FRAME_VISBLE = 'true' // 'true' or 'false'

const QuitHandle = () => {
	app.quit()
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
	app.quit()
}

const createBrowserWindow = (path: string, x?: number, y?: number, devTools?: Electron.OpenDevToolsOptions) => {
	// Get the primary display's dimensions
	const { width: screenWidth } = screen.getPrimaryDisplay().workAreaSize
	const windowWidth = 600 // Set the window width
	const windowHeight = 400 // Set the window height

	// Create the browser window.
	const frameLess = {
		frame: false,
		transparent: true,
		titleBarStyle: 'hidden',
		titleBarOverlay: {
			color: '#2f324188',
			symbolColor: '#74b1be88',
			height: 20,
		},
	}

	const browserOptions = {
		height: windowHeight,
		width: windowWidth,
		x: screenWidth - windowWidth - (x ?? 0),
		y: y,
		webPreferences: {
			nodeIntegration: true,
			contextIsolation: false,
		},
	}

	let finalbrowserOptions = Object.assign({}, browserOptions)
	if (process.env.FRAME_VISBLE !== 'true') {
		finalbrowserOptions = Object.assign(finalbrowserOptions, frameLess)
	}
	const mainWindow = new BrowserWindow(finalbrowserOptions as Electron.BrowserWindowConstructorOptions)

	// and load the index.html of the app.
	mainWindow.loadURL(path)

	// Open the DevTools.
	if (process.env.FRAME_VISBLE !== 'true') {
		mainWindow.setAlwaysOnTop(true, 'normal')
	} else {
		mainWindow.webContents.openDevTools(devTools)
	}
}

const createWindow = (): void => {
	createBrowserWindow(MAIN_WINDOW_WEBPACK_ENTRY, 0, 0)
	createBrowserWindow(CLIENT_WINDOW_WEBPACK_ENTRY, 0, 500)
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
	ipcMain.handle('ping', async () => {
		return 'pong'
	})

	ipcMain.handle('titlebar', async (event) => {
		const win = BrowserWindow.fromWebContents(event.sender)
		if (win !== null) {
			return win.accessibleTitle
		}
		return null
	})

	ipcMain.handle('dark-mode:light', () => {
		if (nativeTheme.shouldUseDarkColors) nativeTheme.themeSource = 'light'
		return nativeTheme.shouldUseDarkColors
	})

	ipcMain.handle('dark-mode:dark', () => {
		if (!nativeTheme.shouldUseDarkColors) nativeTheme.themeSource = 'dark'
		return nativeTheme.shouldUseDarkColors
	})

	ipcMain.on('set-ignore-mouse-events', (event, ignore, options) => {
		const win = BrowserWindow.fromWebContents(event.sender)
		if (win !== null) {
			win.setIgnoreMouseEvents(ignore, options)
		}
	})

	createWindow()
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') QuitHandle()
})

app.on('activate', () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) createWindow()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
